// generated by mistc — do not edit
const rt = require('./mist-rt.js');
rt.observePerf();
App({
  __perf: rt.perfEntries,
  onLaunch() {
  console.log('mist-feed launched')
},
  onError(error) {
  console.error('mist-feed error:', error)
},
  onUnhandledRejection(e) {
  console.error('mist-feed unhandled rejection:', e.reason)
},
});
