// generated by mistc — do not edit
const rt = require('../../mist-rt.js');
const __S0 = require('../../stores/lab.js');
Page({
  data: {
    pageSizeStr: null,
    lab: null,
  },
  setFullRender(...args) {
    return __S0.setFullRender(...args);
  },
  setPageSize(...args) {
    return __S0.setPageSize(...args);
  },
  __derive() {
    const __o = {};
    rt.derive(this, __o, 'pageSizeStr', null, () => __S0.lab.value.pageSize + ' 条/页', ['lab']);
    return __o;
  },
  __set(path, value) {
    rt.set(this, path, value);
  },
  enableFull() {
  this.setFullRender(true)
  wx.switchTab({ url: '/pages/feed/feed' })
},
  disableFull() {
  this.setFullRender(false)
},
  smallerPages() {
  this.setPageSize(__S0.lab.value.pageSize - 20)
},
  biggerPages() {
  this.setPageSize(__S0.lab.value.pageSize + 20)
},
  onLoad() {
    rt.bindStores(this, [[__S0.lab, 'lab']]);
    rt.init(this);
  },
  onUnload() {
    rt.unbindStores(this);
  },
});
