// generated by mistc — do not edit
const rt = require('../mist-rt.js');
const lab = rt.store({ fullRender: false, pageSize: 50 });
function setFullRender(on) {
  lab.__set(`fullRender`, on)
}
function setPageSize(n) {
  if (n >= 10 && n <= 200) {
    lab.__set(`pageSize`, n)
  }
}
module.exports = { lab, setFullRender, setPageSize };
